silly store game hehe<br>
planning to implement python api reading<br>
for now, store data in lists/structs initialised in the script<br><br>
an error keeps cropping up when I ask to list the products I have in the back. here's the error message:<br>
terminate called after throwing an instance of 'std::out_of_range'<br>
  what():  vector::_M_range_check: __n (which is 1) >= this->size() (which is 1)<br>
Aborted<br>
I'm still figuring out a solution!
